server.port=8888
spring.application.name=config-server

# Eureka Server එකට register වීම සඳහා (Mandatory) [cite: 57, 58]
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
# Configuration තබා ගන්නා ආකාරය (Native/Local Profile භාවිතා කරන්නේ නම්)
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config

# Security Disable කිරීම
spring.cloud.config.server.bootstrap=false
management.security.enabled=false
spring.security.user.password=